module CLIIZ
  
  NO_IMAGE = '/images/noimage.jpg'

  module COMPANY
    DESCRIPTION = 'This website is generated by Cliiz Online Website Builder'
    KEYWORDS = 'site generator,online website builder,free website builder'
    TWITTER = ''
    FACEBOOK = ''
  end

  module MENU
    HOME = 'home'
    ABOUT = 'about'
    CONTACT = 'contact'
    BLOG = 'blog'
    GALLERY = 'gallery'
    ITEMS = 
      [ [HOME, '/home', 'Home'], 
        [ABOUT, '/about', 'About'], 
        [CONTACT, '/contact', 'Contact'],
        [BLOG, '/blog', 'Blog'],
        [GALLERY, '/gallery', 'Gallery'] ]
    DEFAULT = [ITEMS[0], ITEMS[1], ITEMS[2]]
    def self.get_item(item)
      ITEMS[ITEMS.index{ |i| i[0]==item }]
    end
  end

  module COMPONENTS
    
    BLOG = 'blog'
    POST = 'post'
    POSTFILTER = 'postfilter'
    IMAGE = 'image'
    GALLERY = 'gallery'
    MAP = 'locationmark'
    FORM = 'infoform'
    CONTENT = 'content'
    SITE = 'sitebuilder'
    YOUTUBE = 'youtube'
    
    class Site
      def self.setting
        { :pages => [ 'home', 'about', 'contact' ] }
      end
    end

    class Content
      def self.setting
        { :content => '<h2>Heading 2</h2><p><i>add some text</i></p>' }
      end
    end

    class Form
      def self.setting
        { 
          :all_fields => [ "name", "email", "url", "phone", "phone2", "address", "subject", "message" ],
          :fields => [ "name", "email", "message"],
          :names => {
            :name => 'fullname',
            :email => 'email', 
            :url => 'website', 
            :phone => 'cellphone_no', 
            :phone2 => 'home_no', 
            :address => 'address', 
            :subject => 'subject', 
            :message => 'message',
            :submit => 'submit'
          },
          :config => {
            :submit_url => '/modules/submit_form',
            :js => 'infoform.js'
          }
        }
      end
    end

    class Map
      def self.setting
        { 
          :address => 'New York, NY, USA', 
          :latlng => [ 40.7143528, -74.0059731 ], 
          :phone => nil, 
          :fax => nil,
          :viewport => [250, 250],
          :config => {
            :js => 'location.js'
          }
        }
      end
    end

    class Blog
      def self.setting
        { :author => nil }
      end
    end
    
    class PostFilter
      LATEST = 'latest'
      MOSTREAD = 'most read'
      RANDOM = 'random'
      def self.setting
        { 
          :size => 3,
          :type => 'latest',
          :tags => '',
          :config => {
            :types => [LATEST, MOSTREAD, RANDOM]
          }
        }
      end
    end

    class Gallery
      def self.setting
        { 
          :display => "basic",
          :config => {
            :js => 'gallery.js',
            :display_types => ["basic", "fancy"]
          }
        }
      end
    end

    class Youtube
      def self.setting
        {
          :code => '',
          :width => 420,
          :height => 315
        }
      end
    end

  end

end
