module CLIIZ
  
  NO_IMAGE = '/assets/noimage.jpg'

  module COMPANY
    DESCRIPTION = 'This website is generated by Cliiz Online Website Builder'
    KEYWORDS = 'site generator,online website builder,free website builder'
    TWITTER = ''
    FACEBOOK = ''
  end

  module COMPONENTS
    
    BLOG = 'blog'
    POST = 'post'
    LISTING = 'list'
    ITEM = 'item'
    POSTFILTER = 'postfilter'
    IMAGE = 'image'
    GALLERY = 'gallery'
    MAP = 'locationmark'
    FORM = 'infoform'
    CONTENT = 'content'
    SITE = 'sitebuilder'
    YOUTUBE = 'youtube'
    
    class Site
      def self.setting
        { :pages => [ 'home', 'about', 'contact' ] }
      end
    end

    class Content
      def self.setting
        { :content => '<h2>Heading 2</h2><p><i>add some text</i></p>' }
      end
    end

    class Form
      VALIDATIONS = [ :email, :phone, :presence ]
      def self.setting
        { 
          :fields => { 0 => [ 1, :name, nil, 'Name', nil] , 1 => [ 2, :email, :email, "Email", nil], 2 => [ 3, :multi_line, nil, "Message", nil] }, # { order => [ id, :type, :validation, 'Name', 'Default Value(s)' ] , }
          :submit => 'Submit',
          :message => 'Thanks for contacting us!',
          :config => {
            :submit_url => '/modules/submit_form',
            :js => 'infoform.js',
            :types => [ [:single_line, nil], [:multi_line, nil], [:name, nil], [:email, :email], [:phone, :phone], [:address, nil] ]
          }
        }
      end
    end

    class Map
      def self.setting
        { 
          :address => 'New York, NY, USA', 
          :latlng => [ 40.7143528, -74.0059731 ], 
          :phone => nil, 
          :fax => nil,
          :viewport => [250, 250],
          :config => {
            :js => 'location.js'
          }
        }
      end
    end

    class Blog
      def self.setting
        { :author => nil }
      end
    end
    
    class PostFilter
      LATEST = 'latest'
      MOSTREAD = 'most read'
      RANDOM = 'random'
      def self.setting
        { 
          :size => 3,
          :type => 'latest',
          :tags => '',
          :config => {
            :types => [LATEST, MOSTREAD, RANDOM]
          }
        }
      end
    end

    class Gallery
      def self.setting
        { 
          :display => "basic",
          :config => {
            :js => 'gallery.js',
            :display_types => ["basic", "fancy"]
          }
        }
      end
    end

    class Youtube
      def self.setting
        {
          :code => '',
          :width => 420,
          :height => 315
        }
      end
    end

    class Listing
      def self.setting
        { :with_price => true, :payable => true, :title => 'List' }
      end
    end

  end

  module MENU
    HOME = 'home'
    ABOUT = 'about'
    CONTACT = 'contact'
    BLOG = CLIIZ::COMPONENTS::BLOG
    GALLERY = CLIIZ::COMPONENTS::GALLERY
    LISTING = CLIIZ::COMPONENTS::LISTING
    FROZEN = [HOME, ABOUT, CONTACT, BLOG, GALLERY, LISTING]
    ITEMS = 
      [ [HOME, '/home', 'Home', true], 
        [ABOUT, '/about', 'About', true], 
        [CONTACT, '/contact', 'Contact', true],
        [BLOG, '/blog', 'Blog', false],
        [GALLERY, '/gallery', 'Gallery', false],
        [LISTING, '/list', 'List', false] ]
    def self.get_item(item)
      ITEMS[ITEMS.index{ |i| i[0]==item }]
    end
  end

  module ERRORS
    
    ENABLE_PACKAGE = { :status => :enable_package, :message => 'Please first enable package!' }

  end  

end
